import { TemplateSummarySchema, type TemplateSummary } from "@ac2/contracts";

export const mockTemplates: TemplateSummary[] = TemplateSummarySchema.array().parse([
  {
    id: "template-launch-campaign",
    name: "Launch campaign hero",
    description: "Primary acquisition layout with room for SKU swaps and seasonal copy.",
    category: "ad",
    width: 1600,
    height: 900,
    status: "live",
    workspaceName: "Growth Studio",
    lastEditedBy: "Anita Rao",
    updatedAt: "2026-04-03T14:10:00.000Z",
    usageCount: 48,
    version: 12,
  },
  {
    id: "template-instagram-drop",
    name: "Instagram drop sequence",
    description: "Nine-panel social run for launches, creator drops, and weekly recaps.",
    category: "social",
    width: 1080,
    height: 1350,
    status: "review",
    workspaceName: "Growth Studio",
    lastEditedBy: "Marcus Lee",
    updatedAt: "2026-04-04T07:30:00.000Z",
    usageCount: 17,
    version: 6,
  },
  {
    id: "template-product-focus",
    name: "Product focus detail",
    description: "Studio crop optimized for performance campaigns and marketplace syndication.",
    category: "product",
    width: 1200,
    height: 1200,
    status: "draft",
    workspaceName: "Retail Ops",
    lastEditedBy: "Nina Shah",
    updatedAt: "2026-04-02T18:45:00.000Z",
    usageCount: 5,
    version: 3,
  },
  {
    id: "template-lifecycle-email",
    name: "Lifecycle email banner",
    description: "Reusable header system for onboarding, retention, and plan upgrade nudges.",
    category: "email",
    width: 1440,
    height: 720,
    status: "archived",
    workspaceName: "Lifecycle",
    lastEditedBy: "Dev Patel",
    updatedAt: "2026-03-28T12:00:00.000Z",
    usageCount: 29,
    version: 9,
  },
]);
